### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by mahdiyari** [FreeJoy-Team/FreeJoyConfigurator#2]
Hi
Basically it doesn't work
I can't save or load from device (it says connected but none works)
I'm on windows 10

**Comment by vostrenkov** [comment]
What says log block in the bottom?

**Comment by mahdiyari** [comment]
nothing
stuck at Requesting config..

**Comment by vostrenkov** [comment]
Did you flash to device hex file from releases or compiled it yourself?

**Comment by mahdiyari** [comment]
I just used your file from releases

**Comment by vostrenkov** [comment]
Give me some time to make clean install and check this

**Comment by mahdiyari** [comment]
do I need to use the "Firmware Programmer" inside app?

**Comment by vostrenkov** [comment]
nope, it is bootloader feature to flash firmware without programmer

**Comment by mahdiyari** [comment]
I will test with another board that I have (this one has different reset button)

**Comment by vostrenkov** [comment]
ok, report please your results

**Comment by mahdiyari** [comment]
The first board displays 128kb flash size in stm32 st-link utility
the second board 64kb flash size

The app seems to work with the second board but still has problems
get config works well I think
If I change buttons and write config, I get "Config written" message but after pressing get config, all buttons revert back to the default settings

**Comment by mahdiyari** [comment]
now it works with the second board
I will appreciate if you fix the problem for the 128kb flash size model too

can I use rotary encoder as joystick with freejoy? I added and it acts like a button

**Comment by vostrenkov** [comment]
I will try to fix 128kB problem in next release. 
You can use encoders as buttons, rotating to one side triggers one button, to other side - another button

**Comment by mahdiyari** [comment]
Can you tell me how can I edit and build freejoy myself?

**Comment by vostrenkov** [comment]
you can use Keil uVision IDE or another option is to build with Makefile with gcc compiler

**Comment by mahdiyari** [comment]
Thank you
what about FreeJoyConfigurator?

**Comment by vostrenkov** [comment]
It is Visual Studio 17 WPF application project
