### ISSUE TITLE
RKJXT1F42001 

### ISSUE THREAD

**Issue by memob777** [FreeJoy-Team/FreeJoyConfigurator#20]
Is possible for somebody to get some help with the legs of the RKJXT1F42001 and how to connect them plz
on the data sheet is a bit confusing

![RKJXT1F42001](https://user-images.githubusercontent.com/70198473/91641072-bdad5200-ea2a-11ea-87c6-9b8ad6e01ace.jpeg)

....  sorry to be so amateur on this
also if i can get your email I like to ask something directly please

**Comment by vostrenkov** [comment]
I use discord for PM about project: Magners#1207

**Comment by vostrenkov** [comment]
![image](https://user-images.githubusercontent.com/21309063/91668407-325cbb00-eb15-11ea-8480-232645321b8d.png)
