### ISSUE TITLE
Shift[2-5] count physical buttons?

### ISSUE THREAD

**Issue by yogggoy** [FreeJoy-Team/FreeJoyConfigurator#23]
https://github.com/FreeJoy-Team/FreeJoyConfigurator/blob/874908a4ec0c864f452e8252a5e07434cec9d9b6/FreeJoyConfigurator/View/ShiftModificatorsView.xaml#L65

Shift flags limited on *physical buttons*, but *logical buttons* can be more.
Shift1 is limited on 128, but other be calculated.

**Comment by vostrenkov** [comment]
Right, thanks

**Comment by vostrenkov** [comment]
Fixed in **v1.6.2b2**

**Comment by yogggoy** [comment]
Thanks you!
