### ISSUE TITLE
Issue sharing latches on 4 shift chains

### ISSUE THREAD

**Issue by nflaum** [FreeJoy-Team/FreeJoyConfigurator#24]
Hello,

I'm having an issue configuring the FreeJoy for 128 buttons using 16 shift registers, with a 4 chain x 4 register configuration. I am trying to use a common latch for all 4 chains.

In the Shift Register tab, everything looks fine. I have 4 chains, each chain has 32 buttons, and each latch pin is assigned to B12.
![Shift_Registers_Tab_OK](https://user-images.githubusercontent.com/71182580/94982789-56376600-04f2-11eb-88fd-ce2ff22b8d9f.png)

However, there is a problem in the Pin Config tab. On the right side, under Current Config, it only shows 32 total buttons. Upon further examination, it is clear that if I set additional ShiftReg_LATCH pins, I notice the number will increase. However, the board I am using has a shared latch for all 4 chains.
![Pin_Config_Tab_Problem](https://user-images.githubusercontent.com/71182580/94982790-59caed00-04f2-11eb-93f2-11fe6aa5e057.png)

In the Button Config tab as well, I only have 32 physical switch to work with, but I should have 128.
![Button_Config_Tab_Problem](https://user-images.githubusercontent.com/71182580/94982804-71a27100-04f2-11eb-9d86-2d256eda8ece.png)

I believe this is a bug. The number of physical buttons is tied to the number of pins set to be ShiftReg_LATCH, but if a common latch is used, the number of buttons need to be multiplies by the number of ShiftReg_DATA pins sharing the latch.

Thanks
Noah

**Comment by vostrenkov** [comment]
Thanks, it will be fixed soon

**Comment by vostrenkov** [comment]
Please check **FreeJoy Configurator v1.6.2b3**

**Comment by nflaum** [comment]
> Please check **FreeJoy Configurator v1.6.2b3**

Thank you very much! Works great. Greatly appreciated.
