### ISSUE TITLE
why can't setup?

### ISSUE THREAD

**Issue by liyayo0927** [FreeJoy-Team/FreeJoyConfigurator#25]
Hello,
When I tried to set up, this problem occurred.
What should I do?

![why can't setup](https://user-images.githubusercontent.com/58555007/96373521-94de4900-119f-11eb-927b-18f79c9b2b56.JPG)

**Comment by vostrenkov** [comment]
You need to install .NET Framework 4.5.2 or newer.
Download link from Microsoft website: https://www.microsoft.com/en-us/download/details.aspx?id=42642

**Comment by vostrenkov** [comment]
Are you trying to install using installator from publish/ folder?
You need to use prebuilt .exe from .zip archive on releases page:
https://github.com/FreeJoy-Team/FreeJoyConfigurator/releases/

And which operating system do you have?

**Comment by liyayo0927** [comment]
I appreciate your message.

_Are you trying to install using installator from publish/ folder?_
Yes. Because I can't found the .exe from FreeJoyConfigurator-master.zip 

_You need to use prebuilt .exe from .zip archive on releases page:
https://github.com/FreeJoy-Team/FreeJoyConfigurator/releases/_
I'm done. And It's working !

_And which operating system do you have?_
I'm use windos10, .NET Framework it's 4.8.03752

**Comment by vostrenkov** [comment]
Nice. I think i should delete this publish folder to prevent such issues
