### ISSUE TITLE
The name in game controller is not change

### ISSUE THREAD

**Issue by liyayo0927** [FreeJoy-Team/FreeJoyConfigurator#27]
Hello,
I have a new issue
Why I change the Device USB name,
but the name in game controller is not change?  
Like this picture.

![ex](https://user-images.githubusercontent.com/58555007/97812341-a81f0780-1cbb-11eb-93e3-65fb4a7c3226.JPG)

**Comment by vostrenkov** [comment]
Hi, this is Windows issue it does not update the name from the descriptor.
To get the name changed you need to rename it in Windows registry or delete the instance:

![unknown-2.png](https://user-images.githubusercontent.com/21309063/97812559-071c5680-1c93-11eb-9fa0-3270a3ef8818.png)

**Comment by liyayo0927** [comment]
Hi, It works !
Thanks a lot for your help !

![ex2](https://user-images.githubusercontent.com/58555007/97815602-25517900-1cca-11eb-8aa9-03f280f574b0.JPG)
