### ISSUE TITLE
When ButtonVcc - no Button Config for it

### ISSUE THREAD

**Issue by godor2008** [FreeJoy-Team/FreeJoyConfigurator#3]
![image](https://user-images.githubusercontent.com/1040630/73617629-51e83f80-4629-11ea-8d0b-d6401f588947.png)

**Comment by vostrenkov** [comment]
Thanks for mentioning this. This bug will be fixed in the next release.
Buttons and axes configuration will be changed a lot in v1.03

**Comment by godor2008** [comment]
Hope for release

**Comment by vostrenkov** [comment]
I have updated archive at the release page. Use 1.2.2.9 version, ButtonVcc is fixed there.
