### ISSUE TITLE
The shift register LATCH/DATA pin is confusing

### ISSUE THREAD

**Issue by jieweiyang** [FreeJoy-Team/FreeJoyConfigurator#5]
In Configuration interface, the LATCH/DATA pin configuration cannot tell which register is related, when there are multiple Shift register group connected.

**Comment by vostrenkov** [comment]
Data/Latch pins for several shift registers groups are mapped sequentialy (pins count starts at A0 and ends at C15). 

For example:
B0 -> Latch
B1 -> Data
C13 -> Data
C14 -> Latch

In this case B0 and B1 are related to first shift register and C13, C14 to second shift register.

I think i can make Latch pin common for all shift registers group (like SCK), i will do this for the next release

**Comment by jieweiyang** [comment]
Understand now, but hopefully this can be proper describe in the configurator.
