### ISSUE TITLE
How do I run the FreeJoyConfigurator?

### ISSUE THREAD

**Issue by tistructor** [FreeJoy-Team/FreeJoyConfigurator#6]
Ciao,
What application do you need to run FreeJoyConfigurator?

**Comment by vostrenkov** [comment]
Hello,
You only need .NET version equal or higher 4.5.1.
Download .zip archive from realizes and run installer

**Comment by tistructor** [comment]
Thanks,
Done.
Great project, I tested the bluepill card and it works great.

**Comment by freakerman21** [comment]
I can't see any installer on that zip

**Comment by vostrenkov** [comment]
Please download .zip archive from releases page: https://github.com/FreeJoy-Team/FreeJoyConfigurator/releases
![image](https://user-images.githubusercontent.com/21309063/78423936-99636a00-7672-11ea-9771-5ebd48dc385e.png)

**Comment by 303HOLY** [comment]
From some reason I can not start configurator. Is it anything what Im doing wrong?
![FREEJOY1](https://user-images.githubusercontent.com/65241363/81714421-f40c9480-946e-11ea-96bd-5eae20d87fa8.jpg)
![FREEJOY2](https://user-images.githubusercontent.com/65241363/81714450-fb33a280-946e-11ea-8fa7-5a6d14cd77f9.jpg)

**Comment by vostrenkov** [comment]
Do you run installer from the archive without unpacking? If yes please unpack it before installing

**Comment by 303HOLY** [comment]
Thanx for reply.
Yes of course first was unziped-unpacked.

**Comment by 303HOLY** [comment]
I unpacked this zip to desktop then when I dubble click setup.exe or when I run it as administrator I have pop up this window as I attached

**Comment by vostrenkov** [comment]
Please try these solutions: https://answers.microsoft.com/en-us/windows/forum/all/your-administrator-has-blocked-this-application/acfb1b75-063b-46f0-a176-06ab7798c9b3
I'd start from turning off UAC. If it wont help then installing in safe mode

**Comment by 303HOLY** [comment]
I've checked two options - still this ugly window pop up :(

**Comment by 303HOLY** [comment]
do I have some virus or something - this is very strange :(

**Comment by 303HOLY** [comment]
Of course any other programs run just perfect

**Comment by vostrenkov** [comment]
I dont think the reason is virus. Quite strange behaviour though. 
Looks like your system dont allow to install not signed software for some reason

**Comment by vostrenkov** [comment]
Have you tried to start it from system explorer but not unreal commander?

**Comment by 303HOLY** [comment]
...Yes I have it unpacked in the folder on my desktop now

**Comment by 303HOLY** [comment]
Probably Ive set something in somewhere in security settings and I have no idea what.
Or somewhere in disck settings

**Comment by 303HOLY** [comment]
But funny things is that everything else is working just perfect

**Comment by 303HOLY** [comment]
Anyway please HELP :)

**Comment by 303HOLY** [comment]
Or like I said maybe I just received some "ugly unwanted person" somewhere in my PC who don't like your beautiful program

**Comment by 303HOLY** [comment]
is it normal that in security is not checked this
![FREEJOY3](https://user-images.githubusercontent.com/65241363/81734313-38a62900-948b-11ea-88d6-c3f93ca0b86c.jpg)

**Comment by 303HOLY** [comment]
this special permissions

**Comment by vostrenkov** [comment]
Running in safe mode usually resolve all permission problems. If it doesn't work for you i can advice you to build it yourself from sources with visual studio

**Comment by 303HOLY** [comment]
first Ill try in safe mode one more time

**Comment by 303HOLY** [comment]
Hello there.
After instaled NEW system everything working just perfect.
Thank you very much for your help but thousands times MORE for this beautiful program.
Regards HOLY
BTW
Is it a way to put longer USB name for my product?

**Comment by vostrenkov** [comment]
Hi, i'm glad to hear you managed to solve your troubles.
USB name lenght is limited by 20 characters. Do you need more?

**Comment by 303HOLY** [comment]
Thx for replay. 
Is it possible to put 30 characters?

**Comment by 303HOLY** [comment]
like that for example:
SimPit303 P-51 Engine Panel

**Comment by 303HOLY** [comment]
Ive notice that from some reason windows do not see all my name but its going to put shorter
is something Im doing wrong?

**Comment by vostrenkov** [comment]
It is not possible in current version of the software. 
But i'm working on new version right now and it will have more memory space allocated for configuration data. So i can extend max USB name lenght to 30 characters

**Comment by 303HOLY** [comment]
in dynamic hid config should I always every time change the PID numer to see the diferent name of my device in windows?

**Comment by 303HOLY** [comment]
...when I decide for example to chage the name of device

**Comment by 303HOLY** [comment]
Vostrenkov are you on Discord : HOTAS/HOSAS/SIMPIT maybe?

**Comment by vostrenkov** [comment]
This is Windows problem, it remember device name at its first connection and does not change it even if it changed in the descriptor.
You have to delete the information about your device from Windows registry to let it change the name.
If you change PID windows just see "new" device and remember its name at first plug

**Comment by vostrenkov** [comment]
Yes, there are subchannel freejoy in that channel. You can find me there as Magners
